---
  - hosts: all
    become: true
    tasks:
      - name: "Installing Java for Jenkins"
        yum: name=java state=latest
      - name: "Adding Jenkins key"
        rpm_key:
          key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
          state: present
          validate_certs: no
      - name: "Get Jenkins repo"
        get_url:
          url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
          dest: /etc/yum.repos.d/jenkins.repo
      - name: "Install Jenkins"
        yum: name=jenkins state=latest
      - name: "Disable setup wizard"
        lineinfile:
          path: /etc/sysconfig/jenkins
          regexp: "{{ item.regexp }}"
          line: "{{ item.line }}"
          mode: u=rw,g=,o=r
        with_items:
          - regexp: '^JENKINS_JAVA_OPTIONS='
            line: "JENKINS_JAVA_OPTIONS=\"-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false\""
          - regexp: '^JENKINS_PORT='
            line: "JENKINS_PORT=8081"
      - name: "Creating groovy scripts to automate jenkins installation"
        file:
          path: /var/lib/jenkins/init.groovy.d
          owner: "jenkins"
          group: "jenkins"
          state: directory
      - name: "Adding groovy scripts"
        copy:
          src: "{{ item }}"
          dest: /var/lib/jenkins/init.groovy.d
        with_items:
          - ./init.groovy.d/security.groovy
          - ./init.groovy.d/installPlugins.groovy
      - name: "Start Jenkins service"
        service:
          name: jenkins
          state: started